inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - db/schema.rb

LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 40

Style/NumericPredicate:
  Enabled: false
